### ISSUE TITLE
formatação errado no XML

### ISSUE THREAD

**Issue by alexcardozo** [marcosgerene/Gerene.Gnre#3]
reparei que no meu XML está faltando as seguintes tags <guias> e <itensGNRE> olhe as classes e vi o seguinte código

Nome do arquivo: LoteGnreRequest.cs 
[DFeCollection("guias")]
[DFeItem(typeof(DadosGnreRequest), "TDadosGNRE")]
public List<DadosGnreRequest> Guias { get; set; }

Nome do arquivo: DadosGnreRequest.cs
[DFeCollection("itensGNRE", Ocorrencia = Ocorrencia.NaoObrigatoria, Ordem = 4)]
[DFeItem(typeof(ItemGnre), "item")]
public List<ItemGnre> Item { get; set; }
public bool ShouldSerializeItensGnre() => Versao == versao2; 

e no local que captura os dados eu coloquei os seguintes códigos

Nome do arquivo: FormDemo.cs
private void BtnRecepcaoLote_Click(object sender, EventArgs e)
		{
			var request = new LoteGnreRequest()
			{
				Versao = "2.00",
				//Versao = "1.00",
				Guias = new List<DadosGnreRequest>()
			};

			//Substitua os dados para realizar o teste
			var dados = new DadosGnreRequest()
			{
				Versao = "2.00",
				//Versao = "1.00",

				/* Atributos da versão selecionada */

				UfFavorecida = "MA",
				TipoGnre = TipoGnre.GnreSimples,
				ContribuinteEmitente = new ContribuinteEmitente()
				{
					IdContribuinteEmitente = new IdContribuinte()
					{
						Cnpj = "13750970000156",
					},
					RazaoSocial = "LOJA CALC. MILANO.COM.BR LTDA",
					//IE = "7023088740084",
					Endereco = "R ANTONIO LOBOSQUI",
					Municipio = 3516200,
					Uf = "SP",
					Cep = "14403638",
					Telefone = "1637059560",

				},

				Item = new List<ItemGnre>()
					{
						new ItemGnre()
						{
							Receita = "100102",
							DetalhamentoReceita = "ICMS Consumidor Final Nao Contribuinte Outra UF por Operacao",
							Produto = "72 - Calcados",
							Referencia = new Referencia
							{
								Mes = 6,
								Ano = 2021
							},

							DocumentoOrigem = new StringTipo()
							{
								Tipo = "10",
								Value = "197841",

							},
							DataVencimento = DateTime.Today,

							Valor = new List<DecimalCampo>()
							{
								new DecimalCampo()
								{
									Value = 31.86M,
									Tipo = "21"

								},
								new DecimalCampo()
								{
									Value = 31.86M,
									Tipo = "11"
								}
							},

							Convenio = "0",

							ContribuinteDestinatario = new ContribuinteDestinatario()
							{
								IdContribuinteEmitente = new IdContribuinte()
								{
									Cpf = "35565810272"
								},
								RazaoSocial = "JOSIMAR SANTOS",
								Municipio = 2105302,
							},

							CamposExtras = new List<CampoExtra2>()
							{
								new CampoExtra2()
								{
									Codigo = 94,
									Valor = "35210513750970000156550010001978411168903898",
								}
							}
						}
					},

				ValorGnre = 31.86M,
				DataPagamento = DateTime.Today
			};

			request.Guias.Add(dados);

			var client = GetClient();

			try
			{
				client.RecepcaoLote(request);
			}
			catch (Exception ex)
			{
				MessageBox.Show(ex.Message);
			}
			finally
			{
				TextXmlEnvio.Text = client.XmlEnvio;
				TextXmlResposta.Text = client.XmlResposta;
			}
		}

**Comment by marcosgerene** [comment]
@alexcardozo

O problema está ligado ao ACBR, mas já foi corrigido, bastava atualizar o pacote nuget do Demo, fiz isso, teste novamente, acredito que terá sucesso.

Tendo sucesso eu lanço uma nova versão Nuget subindo a referencia mínima do ACBr.

**Comment by alexcardozo** [comment]
perfeito o XML está correto

**Comment by marcosgerene** [comment]
Nuget 1.0.3 referenciando a versão corrigida do ACBr está disponível.
