### ISSUE TITLE
referencia/periodo

### ISSUE THREAD

**Issue by JoaoRodrigues94** [marcosgerene/Gerene.Gnre#4]
precisei gerar uma guia para o estado da Bahia porém está me retornando o seguinte erro  
<ns1:motivosRejeicao><ns1:motivo><ns1:codigo>220</ns1:codigo><ns1:descricao>Periodo de apuracao nao informado!</ns1:descricao><ns1:campo>referencia/periodo [item: 1]</ns1:campo></ns1:motivo></ns1:motivosRejeicao>

**Comment by marcosgerene** [comment]
@JoaoRodrigues94 

Você não informou um campo obrigatório. Qual tipo de guia você está gerando?

Exemplo para 100102 e para 100129:
```
meuitem.Referencia = new Gerene.Gnre.Classes.Referencia()
{
	Periodo = "0", //0 - mensal
	Parcela = null,
	Ano = DateTime.Today.Year,
	Mes = DateTime.Today.Month
};
```

Você pode ver melhor estado-a-estado aqui:

http://www.gnre.pe.gov.br/gnre/portal/automacao.jsp#

![image](https://user-images.githubusercontent.com/15945003/134042528-6bd3b522-83c4-4542-ac8d-856c7a8e2dcc.png)


Exemplo para Bahia:

![image](https://user-images.githubusercontent.com/15945003/134042469-0763d29c-6562-4eb3-8177-800de5662bb3.png)

**Comment by JoaoRodrigues94** [comment]
Agradeço a atenção! fiz o que vc me passou deu certo porém agora aparece esse erro!
</ns1:dadosPagamento><ns1:motivosRejeicao><ns1:motivo><ns1:codigo>700</ns1:codigo><ns1:descricao>Campo Documento de origem expandido obrigatorio</ns1:descricao><ns1:campo>item_camposExtras</ns1:campo></ns1:motivo></ns1:motivosRejeicao></ns1:guia></ns1:resultado>

**Comment by JoaoRodrigues94** [comment]
Deu certo era questão de ambiente o CNPJ q eu estou utilizando está dando esse erro em ambiente de homologação mas quando passo pra produção funciona normalmente!

**Comment by marcosgerene** [comment]
@JoaoRodrigues94 sim, existe um problema com a homologação, infelizmente tive que rodar meus testes em produção também.
